# Generated by Django 4.0.4 on 2022-05-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
