# Generated by Django 4.0.4 on 2022-05-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_notes_due_todo_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='due',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='due',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='due',
            new_name='date',
        ),
    ]
